y3owk1n/nix-system-config

- modules/darwin/homebrew/casks.nix
Removed the kawa cask from the homebrew casks list for better organization.
> feat: remove kawa cask in homebrew

- flake.lock
Updated flake.lock with new revisions for home-manager and nixpkgs repositories.
Reason for change was to stay up-to-date with the latest changes in dependencies.
> ci(flake): Update flake.lock with new revisions

- modules/config/nvim/lua/k92/plugins/wilder.lua
Commented out the dependencies declaration in the wilder plugin configuration
to improve code readability and reduce clutter. This declaration is currently
unused and can be safely removed.
> refactor: Comment out unused dependencies in wilder plugin configuration

- modules/config/svim/blacklist
Add Spotlight to the SVIM blacklist in order to prevent it from being launched
accidentally during development.
> feat: Add Spotlight to blacklist in SVIM config

- modules/config/vimari/vimari.json
Changed link hint characters to "htnsgcrl" to improve usability and efficiency in
Vimari.
> feat: Update link hint characters

- modules/config/vimlike/settings.txt
- modules/darwin/homebrew/mas-apps.nix
Add the "Vimlike" extension to the list of MAS apps in the Nix configuration file.
Update the settings.txt file for the Vimlike extension with new key mappings for scrolling, navigation, tab management, video control, dark mode, reload, help, and URL actions.
> feat: Add Vimlike extension and update mappings

- modules/home-manager/programs/tmux/default.nix
Update tmux to commit b26eb2fa for security reasons. New sha256 hash
generated accordingly.
> build(tmux): Update tmux to version b26eb2fa

- modules/config/nvim/lua/k92/plugins/neo-tree.lua
Removed unnecessary key mappings for NeoTree in nvim configuration to simplify
and streamline the key bindings. Also adjusted key mapping for opening NeoTree
in the root directory.
> style: refactor(neo-tree): Simplify key mappings for NeoTree in nvim

- modules/config/nvim/lua/k92/plugins/neo-tree.lua
Add logic to retrieve the correct path to a file or folder in NeoTree based
on the current buffer or current working directory. This ensures that the
NeoTree is always opened at the right location.
> feat(nvim): Add logic to reveal correct file/folder in NeoTree

- flake.lock
Update the home-manager package to version 4cec20d for compatibility and
new features.
> ci(deps): Update home-manager to version 4cec20d

- flake.lock
Updated the revisions and narHash values for nixpkgs, nixpkgs-unstable,
and home-manager in flake.lock file to match the latest changes.
> ci: Update flake.lock with new revisions and narHash values

- flake.nix
Removed the demo Virtual Machine configuration from flake.nix as it is no longer needed.
> refactor: Remove unnecessary demo Virtual Machine configuration

- modules/home-manager/home/packages/default.nix
Enable the luajitPackages.luarocks package for neovim to ensure proper
functionality. Remove commented out line for clarity.
> fix: Enable luajitPackages.luarocks for neovim functionality

- modules/home-manager/home/packages/default.nix
Remove comment disabling luajit in neovim to enable its usage.
> fix: enable luajit in neovim

- modules/darwin/homebrew/casks.nix
Add zerotier-one to the list of applications in the Homebrew casks file to make
it easier for users to install. This software is commonly used and requested by
users.
> feat: Add zerotier-one to Homebrew casks

- modules/config/nvim/lua/k92/core/options.lua
Changed isfnname to isfname in order to correctly set option for considering
string-string as whole words. This fixes an issue where incorrect option
was being used.
> fix(core): fix typo in isfname option

- flake.lock
Update flake.lock with new lastModified timestamps, narHash values, and revision
numbers for nixpkgs and home-manager repositories.
> ci(flake): update flake.lock

- modules/config/nvim/lua/k92/plugins/lspconfig.lua
Customized the handling of hover requests in the LSP configuration to display
markdown content in a floating preview window. This improves the user
experience by providing a more readable and focused display of hover
information.
> feat: Add custom handler for textDocument/hover in LSP config

- modules/config/nvim/lua/k92/plugins/telescope.lua
Added key mappings in telescope configuration to open with and add to trouble list
using <c-a> and <c-A> for insert and normal mode respectively. This enhances
user experience by providing quick access to the trouble list functionalities.
> feat: Add key mappings for opening with and adding to trouble list

- flake.lock
- Update flake.lock with new revisions and narHashes for nixpkgs-unstable
and home-manager repositories.
> build: Update flake.lock with new revisions and narHashes

- modules/home-manager/programs/fish/default.nix
Added neovim as an alias for 'n' command and 'nivm' in the fish shell configuration file.
> feat: Add neovim alias for 'n' command and 'nivm'

- modules/config/nvim/lua/k92/plugins/lspconfig.lua
Changed key mappings for navigating between diagnostic messages to <C-j>
for going to the previous message and <C-k> for going to the next message. 
Updated the corresponding comments for clarity.
> refactor: Update key mappings for diagnostic navigation

- modules/config/nvim/lua/k92/plugins/nvim-treesitter.lua
Enabled query linter in nvim-treesitter for better code linting. Uses virtual
text and triggers linting on BufWrite and CursorHold events.
> feat: Enable query linter in nvim-treesitter

- modules/config/nvim/lua/k92/plugins/telescope.lua
In the telescope plugin configuration, update mappings to prevent any
actions during insert mode for a smoother user experience. Remove unused
keymap set for finding files. Change initial mode to insert for file
browser opening.
> refactor: update mappings to prevent actions during insert mode

- modules/config/nvim/lua/k92/plugins/telescope.lua
Added a keymap for opening the Telescope cmdline extension in the Telescope plugin
and loaded the cmdline extension for Telescope.
> feat(telescope): Add keymap for Telescope cmdline extension and load cmdline extension

- modules/config/nvim/lua/k92/plugins/telescope.lua
Removed unnecessary keymap for Telescope cmdline and updated description
for opening the file browser. Also removed loading of the cmdline extension
as it is no longer needed. Keymap configurations for searching Neovim config
and notifications were adjusted for better clarity and consistency.
> feat: Refactor Telescope keymap configuration

- modules/config/nvim/lua/k92/core/autocmds.lua
Removed autocmds for setting cmdheight to 2 when entering a macro and 0 when leaving,
which are no longer needed as they were causing conflicts with other configurations.
> refactor: Remove unnecessary autocmds for macro recording

- modules/config/nvim/lua/k92/plugins/telescope.lua
Removed unused key bindings for searching files and current buffer fuzzy search in the Telescope plugin configuration file to declutter the keymap setup.
> refactor: Remove unused key bindings for file searching

- flake.lock
Updated flake.lock with new revisions and narHash values for nixpkgs and home-manager flake inputs.
> build(flake): update flake.lock

- flake.lock
Updated the `flake.lock` file to reflect the changes in the last modified
timestamps, Nix hashes, and revisions for `nixpkgs-unstable`, `nixpkgs`,
and `home-manager` repositories.
> build: Update flake lock files

- modules/config/nvim/lua/k92/plugins/lspconfig.lua
Changed key mappings for navigating between previous and next diagnostic
messages to use more intuitive key bindings: [d for previous diagnostic and
]d for next diagnostic. This improves user experience and efficiency.
> feat: Update key mappings for diagnostic messages

- modules/config/nvim/lua/config/options.lua
Lazyvim default localleader is '/', switch to ',' as '/' is interfering with `searches`
> feat: use ',' as localleader
