y3owk1n/nix-system-config

modules/home-manager/programs/fish/default.nix

Added the nvi alias to default.nix for neovim.

feat: Add nvi alias to default.nix

---

modules/config/firefox/user.js

Update font preferences to use "Geist" for sans-serif font and "GeistMono Nerd Font Mono" for monospace font in user.js. Remove commented-out code for serif font.

feat: Update fonts in user.js

---

modules/config/vimari/vimari.json

Changed link hint characters to "aoeusnthid" and updated key bindings for
toggle hints to "f" and "shift+f" to improve user experience and productivity.

feat: Update Vimari linkhint characters and key bindings

---

modules/home-manager/programs/alacritty/default.nix

Set the startup mode for Alacritty to Maximized for better user experience.

feat: Set Alacritty startup mode to Maximized

---

modules/darwin/homebrew/casks.nix
modules/darwin/system/default.nix

Commented out the configurations for "com.raycast.macos" in the default.nix file to temporarily disable them. This is to troubleshoot an issue related to these configurations.

feat: Commented out raycast configurations

---

modules/home-manager/programs/bat/default.nix

Changed the revision and sha256 of the bat theme to match the latest version.

build: Update bat theme to latest version

---

modules/config/nvim/lua/k92/plugins/neo-tree.lua
modules/config/nvim/lua/k92/plugins/oil.lua
modules/config/nvim/lua/k92/utils/lsp.lua

oil keep crashing with scheme not found, come back later when its ok

feat: switch to neo-tree from oil

---

modules/config/nvim/lua/k92/plugins/spectre.lua

Added nvim-spectre plugin with custom key mapping for replacing in files.

feat: Add nvim-spectre plugin

---

modules/config/nvim/lua/k92/plugins/neo-tree.lua

Add harpoon navigation index component to neo-tree renderer to visually
indicate the position of current file in harpoon navigation list. This
enhances navigation experience within the tree.

feat: Add harpoon navigation index component to neo-tree

---

modules/config/nvim/lua/k92/plugins/none-ls.lua

Add configuration for eslint code actions and diagnostics as well as yamllint diagnostics to enhance linting capabilities in the project.

feat: Add null-ls configuration for eslint and yamllint

---

modules/config/nvim/lua/k92/core/keymaps.lua
modules/config/nvim/lua/k92/core/options.lua

Add `undodir` option pointing to `os.getenv("HOME") .. "/.vim/undodir"` 
and append `@-@` to `isfnname`.

feat(options): add undodir option and isfnname entry

---

modules/config/nvim/lua/k92/lazy.lua
modules/config/nvim/lua/k92/plugins/colorscheme.lua
modules/config/nvim/lua/k92/plugins/lspconfig.lua
modules/config/nvim/lua/k92/plugins/nvim-notify.lua
modules/config/nvim/lua/k92/plugins/telescope.lua
modules/config/nvim/lua/k92/utils/lsp.lua

- Added keymap for showing notifications using <leader>sn
- Added extension for notifying using telescope
- Included configuration for plugin updates notification in lazy setup
- Set notify option to true in colorscheme configuration
- Added configuration for notifications in nvim-notify plugin

feat: Add notification functionality to Neovim config

---

modules/config/nvim/lua/k92/plugins/telescope.lua

Improve the descriptions of the telescope keymap bindings for searching
resume and config files. Update the keymap descriptions for better clarity
and consistency.

feat: Improve telescope keymap descriptions

---

modules/config/nvim/lua/k92/core/options.lua

Add wildignore option to ignore node_modules directory and append path for searching in options.

feat: Add wildignore for node_modules and path for searching in options

---

modules/config/nvim/lua/k92/plugins/telescope.lua

Changed the keymap to use <leader>e for opening the file browser.
Also updated the keymap for <leader><space> to open file browser from cwd.

feat(telescope): Update keymap for opening File Browser

---

modules/home-manager/programs/tmux/default.nix

Updated the path to the tmux configuration file in the tmux default.nix
file to ~/.config/tmux.conf for consistency with file structure.

chore: Update tmux configuration file path in tmux default.nix

---

modules/darwin/homebrew/brews.nix

Add gnu-sed package to the list of brews in order to improve compatibility with certain scripts.

feat: Add gnu-sed to brews

---

modules/config/nvim/lua/k92/plugins/nvim-treesitter.lua

feat: temporary remove lhs & rhs assignment

---

modules/darwin/homebrew/casks.nix
modules/home-manager/programs/alacritty/default.nix
modules/home-manager/xdg/default.nix

- **feat: remove wezterm**
- **feat: enable alacritty**

switch alacritty

---

modules/config/alacritty/alacritty.toml
modules/config/alacritty/catppuccin-macchiato.toml
modules/darwin/homebrew/casks.nix
modules/home-manager/programs/alacritty/default.nix
modules/home-manager/xdg/default.nix

- **feat(alacritty): migrate from nix to brew and xdg config**
- **feat: init alacritty config**

feat: migrate alacritty to brew & xdg controlled instead of nix

---

modules/config/aerospace/aerospace.toml
modules/darwin/homebrew/casks.nix
modules/darwin/services/skhd.nix
modules/darwin/services/yabai.nix
modules/home-manager/xdg/default.nix

- **feat: remove yabai**
- **feat: add aerospace**

feat: use aerespace as tilin manager

---

modules/config/aerospace/aerospace.toml

If not it will show 0 during startup

feat(aerospace): focus to workspace 1 on startup
